fix: remove duplicate case-insensitve columns
This fixes the following error:

```
Error: error returned from database: (code: 1) duplicate column name: metadata_meal

Caused by:
    (code: 1) duplicate column name: metadata_meal
```

In this instance, metadata_Meal and metadata_meal are both present in the data. metadata_Meal will be used.